#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
HAR_FILE="${PROJECT_DIR}/form/build/default/outputs/default/form.har"

if [[ ! -f "${HAR_FILE}" ]]; then
  echo "HAR not found: ${HAR_FILE}" >&2
  exit 1
fi
tar -tzf "${HAR_FILE}" >/dev/null

PACKAGE_JSON="$(tar -xOzf "${HAR_FILE}" package/oh-package.json5)"
MODULE_JSON="$(tar -xOzf "${HAR_FILE}" package/src/main/module.json)"
ENTRY_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/Index.d.ets)"
CONTROLLER_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormController.d.ets)"
ARRAY_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormArray.d.ets)"
FIELD_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormField.d.ets)"
INFERENCE_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormFieldInference.d.ets)"
PATH_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormPath.d.ets)"
RENDERER_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormRenderer.d.ets)"
SLOTS_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormSlots.d.ets)"
ERRORS_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormErrors.d.ets)"
LAYOUT_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormLayout.d.ets)"
STRUCTURE_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormStructure.d.ets)"
FIELD_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/core/FormField.d.ets)"
VIEW_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/components/HmFormView.d.ets)"
ARRAY_VIEW_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/components/HmFormArrayView.d.ets)"
THEME_DECLARATION="$(tar -xOzf "${HAR_FILE}" package/src/main/ets/theme/HmFormTheme.d.ets)"
CONTENTS="$(tar -tzf "${HAR_FILE}")"

grep -Eq '"name"[[:space:]]*:[[:space:]]*"@hmkit/form"' <<<"${PACKAGE_JSON}"
grep -Eq '"version"[[:space:]]*:[[:space:]]*"0\.1\.1"' <<<"${PACKAGE_JSON}"
grep -Eq '"@hmkit/validator"[[:space:]]*:[[:space:]]*"\^1\.0\.0"' <<<"${PACKAGE_JSON}"
grep -Eq '"debug"[[:space:]]*:[[:space:]]*false' <<<"${MODULE_JSON}"
grep -Fq '"2in1"' <<<"${MODULE_JSON}"
grep -Fq 'export { FormController, FormControllerOptions }' <<<"${ENTRY_DECLARATION}"
grep -Fq 'FormArrayController, FormArrayControllerOptions, FormArrayEntry, FormArrayIdentity, HmFormArrayItemContext' <<<"${ENTRY_DECLARATION}"
grep -Fq 'export { HmFormView }' <<<"${ENTRY_DECLARATION}"
grep -Fq 'export { HmFormArrayView }' <<<"${ENTRY_DECLARATION}"
grep -Fq 'export { HmFormTheme, HmFormThemeOptions }' <<<"${ENTRY_DECLARATION}"
grep -Fq 'FormFieldUIOptions, FormOptionsLoader, FormTextInputType, FormSelectOption' <<<"${ENTRY_DECLARATION}"
grep -Fq 'HmFormFieldRenderContext, HmFormFieldRenderer, HmFormRendererRegistry' <<<"${ENTRY_DECLARATION}"
grep -Fq 'export { HmFormSubmitSlotContext }' <<<"${ENTRY_DECLARATION}"
grep -Fq 'HmFormErrorSummaryContext, HmFormErrorSummaryItem, buildFormErrorSummaryItems' <<<"${ENTRY_DECLARATION}"
grep -Fq 'export { HmFormLayout, HmFormLayoutOptions }' <<<"${ENTRY_DECLARATION}"
grep -Fq 'FormSectionOptions, FormSectionSpec, FormStepOptions, FormStepSpec, FormStructureController' <<<"${ENTRY_DECLARATION}"
grep -Fq 'FormFieldInferenceOptions, FormFieldInferenceResult, inferFormFields' <<<"${ENTRY_DECLARATION}"
grep -Fq 'export { getFormValue, setFormValue }' <<<"${ENTRY_DECLARATION}"
grep -Fq 'export declare class FormController' <<<"${CONTROLLER_DECLARATION}"
grep -Fq 'validating: Record<string, boolean>;' <<<"${CONTROLLER_DECLARATION}"
grep -Fq 'optionValues: Record<string, FormSelectOption[]>;' <<<"${CONTROLLER_DECLARATION}"
grep -Fq 'optionsLoading: Record<string, boolean>;' <<<"${CONTROLLER_DECLARATION}"
grep -Fq 'optionErrors: Record<string, string>;' <<<"${CONTROLLER_DECLARATION}"
grep -Eq 'getFieldState\([^)]*: string\): FormFieldState;' <<<"${CONTROLLER_DECLARATION}"
grep -Eq 'getOptions\([^)]*: string\): FormSelectOption\[\];' <<<"${CONTROLLER_DECLARATION}"
grep -Fq 'loadAllOptions(): void;' <<<"${CONTROLLER_DECLARATION}"
grep -Eq 'loadOptions\([^)]*: string\): Promise<void>;' <<<"${CONTROLLER_DECLARATION}"
grep -Eq 'syncValues\([^)]*: Record<string, Object>\): boolean;' <<<"${CONTROLLER_DECLARATION}"
grep -Eq 'validateFields\([^)]*: string\[\]\): Promise<Record<string, string>>;' <<<"${CONTROLLER_DECLARATION}"
grep -Eq 'firstErrorName\([^)]*\?: string\[\]\): string \| undefined;' <<<"${CONTROLLER_DECLARATION}"
grep -Fq 'export type FormArrayIdentity = (value: Object, index: number) => string;' <<<"${ARRAY_DECLARATION}"
grep -Fq 'export interface FormArrayControllerOptions' <<<"${ARRAY_DECLARATION}"
grep -Fq 'export declare class FormArrayEntry' <<<"${ARRAY_DECLARATION}"
grep -Fq 'export declare class FormArrayController' <<<"${ARRAY_DECLARATION}"
grep -Fq 'entries: FormArrayEntry[];' <<<"${ARRAY_DECLARATION}"
grep -Fq 'getValues(): Object[];' <<<"${ARRAY_DECLARATION}"
grep -Eq 'insert\([^)]*: number, [^)]*: Object\): boolean;' <<<"${ARRAY_DECLARATION}"
grep -Eq 'move\([^)]*: number, [^)]*: number\): boolean;' <<<"${ARRAY_DECLARATION}"
grep -Eq 'syncValues\([^)]*: Object\[\]\): boolean;' <<<"${ARRAY_DECLARATION}"
grep -Fq 'export declare class HmFormArrayItemContext' <<<"${ARRAY_DECLARATION}"
grep -Fq 'readonly key: string;' <<<"${ARRAY_DECLARATION}"
grep -Fq 'moveUp(): void;' <<<"${ARRAY_DECLARATION}"
grep -Fq 'moveDown(): void;' <<<"${ARRAY_DECLARATION}"
grep -Fq 'static readonly TEXTAREA: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'static readonly SELECT: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'static readonly RADIO: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'static readonly CHECKBOX: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'static readonly SWITCH: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'static readonly DATE: string;' <<<"${FIELD_DECLARATION}"
grep -Eq 'static custom\([^)]*: string\): string;' <<<"${FIELD_DECLARATION}"
grep -Eq 'static isCustom\([^)]*: string\): boolean;' <<<"${FIELD_DECLARATION}"
grep -Fq 'export declare class FormFieldSlot' <<<"${FIELD_DECLARATION}"
grep -Fq 'static readonly PREFIX: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'static readonly SUFFIX: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'static readonly LABEL: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'static readonly HELP: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'static readonly ERROR: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'export type FormCondition' <<<"${FIELD_DECLARATION}"
grep -Fq 'export declare class FormSelectOption' <<<"${FIELD_DECLARATION}"
grep -Fq 'export type FormOptionsLoader = () => Promise<FormSelectOption[]>;' <<<"${FIELD_DECLARATION}"
grep -Fq 'export interface FormFieldUIOptions' <<<"${FIELD_DECLARATION}"
grep -Fq 'visibleWhen?: FormCondition;' <<<"${FIELD_DECLARATION}"
grep -Fq 'disabledWhen?: FormCondition;' <<<"${FIELD_DECLARATION}"
grep -Fq 'slots?: string[];' <<<"${FIELD_DECLARATION}"
grep -Fq 'readonly slots: string[];' <<<"${FIELD_DECLARATION}"
grep -Fq 'span?: number;' <<<"${FIELD_DECLARATION}"
grep -Fq 'readonly span: number;' <<<"${FIELD_DECLARATION}"
grep -Fq 'optionsLoader?: FormOptionsLoader;' <<<"${FIELD_DECLARATION}"
grep -Fq 'readonly optionsLoader: FormOptionsLoader | undefined;' <<<"${FIELD_DECLARATION}"
grep -Eq 'usesSlot\([^)]*: string\): boolean;' <<<"${FIELD_DECLARATION}"
grep -Eq 'loadsOptions\(\): boolean;' <<<"${FIELD_DECLARATION}"
grep -Eq 'selectIndex\([^)]*: Object \| undefined, [^)]*\?: FormSelectOption\[\]\): number;' <<<"${FIELD_DECLARATION}"
grep -Eq 'selectValue\([^)]*: number, [^)]*\?: FormSelectOption\[\]\): string \| undefined;' <<<"${FIELD_DECLARATION}"
grep -Eq 'selectLabel\([^)]*: Object \| undefined, [^)]*\?: FormSelectOption\[\]\): string;' <<<"${FIELD_DECLARATION}"
grep -Eq 'checkboxValues\([^)]*: Object \| undefined, [^)]*\?: FormSelectOption\[\]\): string\[\];' <<<"${FIELD_DECLARATION}"
grep -Eq 'isOptionSelected\([^)]*: Object \| undefined, [^)]*: string, [^)]*\?: FormSelectOption\[\]\): boolean;' <<<"${FIELD_DECLARATION}"
grep -Eq 'toggleOptionValue\([^)]*: Object \| undefined, [^)]*: string, [^)]*: boolean, [^)]*\?: FormSelectOption\[\]\): string\[\];' <<<"${FIELD_DECLARATION}"
grep -Eq 'isVisible\([^)]*: Record<string, Object>\): boolean;' <<<"${FIELD_DECLARATION}"
grep -Eq 'isDisabled\([^)]*: Record<string, Object>\): boolean;' <<<"${FIELD_DECLARATION}"
grep -Eq 'dateModelValue\([^)]*: Date\): string;' <<<"${FIELD_DECLARATION}"
grep -Eq 'dateSelected\([^)]*: Object \| undefined\): Date;' <<<"${FIELD_DECLARATION}"
grep -Fq 'export interface FormFieldInferenceOptions' <<<"${INFERENCE_DECLARATION}"
grep -Fq 'export declare class FormFieldInferenceResult' <<<"${INFERENCE_DECLARATION}"
grep -Fq 'getInitialValues(): Record<string, Object>;' <<<"${INFERENCE_DECLARATION}"
grep -Fq 'export declare function inferFormFields' <<<"${INFERENCE_DECLARATION}"
grep -Eq 'export declare function getFormValue\([^)]*: Record<string, Object>, [^)]*: string\): Object \| undefined;' <<<"${PATH_DECLARATION}"
grep -Eq 'export declare function setFormValue\([^)]*: Record<string, Object>, [^)]*: string, [^)]*: Object \| undefined\): Record<string, Object>;' <<<"${PATH_DECLARATION}"
grep -Fq 'export declare class HmFormFieldRenderContext' <<<"${RENDERER_DECLARATION}"
grep -Fq 'export type HmFormFieldRenderer = WrappedBuilder<' <<<"${RENDERER_DECLARATION}"
grep -Fq 'export declare class HmFormRendererRegistry' <<<"${RENDERER_DECLARATION}"
grep -Eq 'register\([^)]*: string, [^)]*: HmFormFieldRenderer\): HmFormRendererRegistry;' <<<"${RENDERER_DECLARATION}"
grep -Eq 'matching\([^)]*: string\): HmFormFieldRenderer\[\];' <<<"${RENDERER_DECLARATION}"
grep -Eq 'assertFields\([^)]*: FormFieldSpec\[\]\): void;' <<<"${RENDERER_DECLARATION}"
grep -Fq 'export declare class HmFormSubmitSlotContext' <<<"${SLOTS_DECLARATION}"
grep -Fq 'readonly submitting: boolean;' <<<"${SLOTS_DECLARATION}"
grep -Fq 'readonly submit: () => void;' <<<"${SLOTS_DECLARATION}"
grep -Fq 'export declare class HmFormErrorSummaryItem' <<<"${ERRORS_DECLARATION}"
grep -Fq 'readonly sectionId: string;' <<<"${ERRORS_DECLARATION}"
grep -Fq 'readonly stepId: string;' <<<"${ERRORS_DECLARATION}"
grep -Fq 'location(): string;' <<<"${ERRORS_DECLARATION}"
grep -Fq 'export declare class HmFormErrorSummaryContext' <<<"${ERRORS_DECLARATION}"
grep -Fq 'readonly activate: (name: string) => void;' <<<"${ERRORS_DECLARATION}"
grep -Fq 'export declare function buildFormErrorSummaryItems' <<<"${ERRORS_DECLARATION}"
grep -Fq 'export interface HmFormLayoutOptions' <<<"${LAYOUT_DECLARATION}"
grep -Fq 'export declare class HmFormLayout' <<<"${LAYOUT_DECLARATION}"
grep -Fq 'readonly breakpoint: string;' <<<"${LAYOUT_DECLARATION}"
grep -Fq 'readonly columnGap: number;' <<<"${LAYOUT_DECLARATION}"
grep -Fq 'readonly rowGap: number;' <<<"${LAYOUT_DECLARATION}"
grep -Fq 'static responsive(): HmFormLayout;' <<<"${LAYOUT_DECLARATION}"
grep -Fq 'export interface FormSectionOptions' <<<"${STRUCTURE_DECLARATION}"
grep -Fq 'export declare class FormSectionSpec' <<<"${STRUCTURE_DECLARATION}"
grep -Fq 'export declare class FormStepSpec' <<<"${STRUCTURE_DECLARATION}"
grep -Fq 'export declare class FormStructureController' <<<"${STRUCTURE_DECLARATION}"
grep -Fq 'currentStepIndex: number;' <<<"${STRUCTURE_DECLARATION}"
grep -Fq 'expandedSections: Record<string, boolean>;' <<<"${STRUCTURE_DECLARATION}"
grep -Eq 'revealField\([^)]*: string\): boolean;' <<<"${STRUCTURE_DECLARATION}"
grep -Eq 'sectionForField\([^)]*: string\): FormSectionSpec \| undefined;' <<<"${STRUCTURE_DECLARATION}"
grep -Eq 'stepForField\([^)]*: string\): FormStepSpec \| undefined;' <<<"${STRUCTURE_DECLARATION}"
grep -Fq 'export declare struct HmFormView' <<<"${VIEW_DECLARATION}"
grep -Fq 'onSubmit: (values: Record<string, Object>) => void;' <<<"${VIEW_DECLARATION}"
grep -Fq 'onInvalid: (errors: Record<string, string>) => void;' <<<"${VIEW_DECLARATION}"
grep -Fq 'readonly renderers: HmFormRendererRegistry;' <<<"${VIEW_DECLARATION}"
grep -Fq 'readonly layout: HmFormLayout;' <<<"${VIEW_DECLARATION}"
grep -Fq 'readonly structure: FormStructureController | undefined;' <<<"${VIEW_DECLARATION}"
grep -Fq 'keepAlive?: boolean;' <<<"${FIELD_DECLARATION}"
grep -Fq 'readonly keepAlive: boolean;' <<<"${FIELD_DECLARATION}"
grep -Fq 'export declare class FormTextInputType' <<<"${FIELD_DECLARATION}"
grep -Fq 'inputType?: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'readonly inputType: string;' <<<"${FIELD_DECLARATION}"
grep -Fq 'readonly showErrorSummary: boolean;' <<<"${VIEW_DECLARATION}"
grep -Fq 'prefix: (context: HmFormFieldRenderContext) => void;' <<<"${VIEW_DECLARATION}"
grep -Fq 'suffix: (context: HmFormFieldRenderContext) => void;' <<<"${VIEW_DECLARATION}"
grep -Fq 'label: (context: HmFormFieldRenderContext) => void;' <<<"${VIEW_DECLARATION}"
grep -Fq 'help: (context: HmFormFieldRenderContext) => void;' <<<"${VIEW_DECLARATION}"
grep -Fq 'error: (context: HmFormFieldRenderContext) => void;' <<<"${VIEW_DECLARATION}"
grep -Fq 'submit: (context: HmFormSubmitSlotContext) => void;' <<<"${VIEW_DECLARATION}"
grep -Fq 'errorSummary: (context: HmFormErrorSummaryContext) => void;' <<<"${VIEW_DECLARATION}"
grep -Fq 'export declare struct HmFormArrayView' <<<"${ARRAY_VIEW_DECLARATION}"
grep -Fq 'readonly values: Object[];' <<<"${ARRAY_VIEW_DECLARATION}"
grep -Fq '$values: (values: Object[]) => void;' <<<"${ARRAY_VIEW_DECLARATION}"
grep -Fq 'item: (context: HmFormArrayItemContext) => void;' <<<"${ARRAY_VIEW_DECLARATION}"
grep -Fq 'export declare class HmFormTheme' <<<"${THEME_DECLARATION}"
grep -Fq 'static light(): HmFormTheme;' <<<"${THEME_DECLARATION}"
grep -Fq 'static dark(): HmFormTheme;' <<<"${THEME_DECLARATION}"
grep -Fxq 'package/README.md' <<<"${CONTENTS}"
grep -Fxq 'package/CHANGELOG.md' <<<"${CONTENTS}"
grep -Fxq 'package/LICENSE' <<<"${CONTENTS}"

if grep -Eq '(^|/)(entry|oh_modules|\.test|BuildProfile|build-profile\.json5|local\.properties|[^/]*(key|keystore|p12|cer|pem)[^/]*)($|/)' <<<"${CONTENTS}"; then
  echo "HAR contains forbidden development or credential-like paths:" >&2
  grep -E '(^|/)(entry|oh_modules|\.test|BuildProfile|build-profile\.json5|local\.properties|[^/]*(key|keystore|p12|cer|pem)[^/]*)($|/)' <<<"${CONTENTS}" >&2
  exit 1
fi

echo "HAR metadata, public declarations, release flag, and contents passed."
